# Generated by Django 5.2.18 on 2026-10-08 08:19

import apps.properties.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex. : T3 lumineux avec balcon', max_length=120, verbose_name='titre')),
                ('kind', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain'), ('local', 'Local commercial')], default='appartement', max_length=20, verbose_name='type de bien')),
                ('transaction', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], default='vente', max_length=10, verbose_name='transaction')),
                ('price', models.PositiveIntegerField(help_text='Prix de vente, ou loyer mensuel charges comprises', verbose_name='prix (€)')),
                ('surface', models.PositiveIntegerField(verbose_name='surface (m²)')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='nombre de pièces')),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, verbose_name='dont chambres')),
                ('neighborhood', models.CharField(max_length=80, verbose_name='quartier')),
                ('highlights', models.TextField(blank=True, help_text='Un point fort par ligne', verbose_name='points forts')),
                ('notes', models.TextField(blank=True, help_text="Étage, chauffage, DPE, travaux, proximité... Tout ce qui peut aider l'IA à rédiger l'annonce.", verbose_name='informations complémentaires')),
                ('listing_text', models.TextField(blank=True, verbose_name="texte de l'annonce")),
                ('listing_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='annonce générée le')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié sur le site')),
                ('slug', models.SlugField(editable=False, max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='agent responsable')),
            ],
            options={
                'verbose_name': 'bien',
                'verbose_name_plural': 'biens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.properties.models.photo_upload_path, verbose_name='photo')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property', verbose_name='bien')),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['position', 'id'],
            },
        ),
    ]
