# Generated by Django 5.2.18 on 2026-10-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(blank=True, verbose_name='réponse')),
                ('status', models.CharField(choices=[('answered', 'Répondu'), ('out_of_scope', 'Hors sujet'), ('error', 'Erreur IA')], default='answered', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='posée le')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='properties.property', verbose_name='bien consulté')),
            ],
            options={
                'verbose_name': 'question client',
                'verbose_name_plural': 'questions clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
